insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("apple", "fruit", 1, "sunkist", 100, "꿀 사과")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("banana", "fruit", 2, "sunkist", 40, "달달한 바나나")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("watermelon", "fruit", 5, "sunkist", 20, "속이 꽉찬 수박")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("tomato", "fruit", 3, "sunkist", 50, "짭짤한 토마토")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("mushroom", "vegetable", 2, "롯데", 80, "맛있는 버섯")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("pepper", "vegetable", 1, "롯데", 90, "매콤한 고추")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("carrot", "vegetable", 2, "롯데", 50, "싱싱한 당근")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("pork", "meat", 4, "한돈", 30, "육즙이 많아요")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("chicken", "meat", 4, "BHC", 40, "바삭바삭")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("beef", "meat", 6, "의성마늘소", 20, "입안에서 녹아요")
